### ISSUE TITLE
Server Crash - PLEASE HELP ( 1.12.2 )

### ISSUE THREAD

**Issue by rochaafk** [przemykomo/simple-planes#141]
The server crashed when i used the Spreyer. Now i can't start my server without crashing.

Time: 08/10/22 14:11
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.block.state.IBlockState.func_185895_e()Z
	at xyz.przemyk.simpleplanes.upgrades.sprayer.SprayerUpgrade.fire_fight(SprayerUpgrade.java:160)
	at xyz.przemyk.simpleplanes.upgrades.sprayer.SprayerUpgrade.tick(SprayerUpgrade.java:99)
	at xyz.przemyk.simpleplanes.entities.PlaneEntity.tickUpgrades(PlaneEntity.java:598)
	at xyz.przemyk.simpleplanes.entities.PlaneEntity.func_70071_h_(PlaneEntity.java:506)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at xyz.przemyk.simpleplanes.upgrades.sprayer.SprayerUpgrade.fire_fight(SprayerUpgrade.java:160)
	at xyz.przemyk.simpleplanes.upgrades.sprayer.SprayerUpgrade.tick(SprayerUpgrade.java:99)
	at xyz.przemyk.simpleplanes.entities.PlaneEntity.tickUpgrades(PlaneEntity.java:598)
	at xyz.przemyk.simpleplanes.entities.PlaneEntity.func_70071_h_(PlaneEntity.java:506)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: simpleplanes:plane (xyz.przemyk.simpleplanes.entities.PlaneEntity)
	Entity ID: 31
	Entity Name: Acacia Plane
	Entity's Exact location: -172,91, 83,56, -59,71
	Entity's Block location: World: (-173,83,-60), Chunk: (at 3,5,4 in -11,-4; contains blocks -176,0,-64 to -161,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0,27, 0,04, 0,30
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 193957083038181091
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-70,64,47), Chunk: (at 10,4,15 in -5,2; contains blocks -80,0,32 to -65,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 12967376 game time, 51584 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 107444 (now: false), thunder time: 57846 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 445283192 bytes (424 MB) / 819986432 bytes (782 MB) up to 819986432 bytes (782 MB)
	JVM Flags: 2 total; -Xms800M -Xmx800m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	Loaded coremods (and transformers): 
SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.0.19-forge-mc1.12.jar)
  
offlineskins (OfflineSkins-1.12.2-v6-core.jar)
  lain.mods.skins.init.forge.asm.ASMTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 3; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by przemykomo** [comment]
Sorry, the 1.12 version of the mod isn't being worked on. I can only suggest to you to use a backup if you have any, remove the plane with external tools or remove the mod altogether so that forge removes all planes from the world.

**Comment by rochaafk** [comment]
That's exaclty what I did. But I just wanna know why it crashes to know how to fix it.
But thanks anywhay!
