### ISSUE TITLE
1.19.2 crashes when firing missile from cgm

### ISSUE THREAD

**Issue by Denali007** [przemykomo/simple-planes#180]
I see this issue has already been fixed for 1.20.x
Is there any chance to apply this patch for 1.19.2?
I really love this mod and it woul;d be even greater with missiles!

**Comment by josemunoz18** [comment]
The error is the following:

java.lang.NoSuchMethodError: 'net.minecraftforge.network.simple.SimpleChannel com.mrcrayfish.guns.network.PacketHandler.getPlayChannel()'
	at xyz.przemyk.simpleplanes.compat.MrCrayfishGunCompat.shooterBehaviour(MrCrayfishGunCompat.java:89) ~[simpleplanes-1.19.2-5.2.2.jar%23270!/:1.19.2-5.2.2] {re:classloading}
	at xyz.przemyk.simpleplanes.upgrades.shooter.ShooterUpgrade.lambda$use$2(ShooterUpgrade.java:108) ~[simpleplanes-1.19.2-5.2.2.jar%23270!/:1.19.2-5.2.2] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at xyz.przemyk.simpleplanes.upgrades.shooter.ShooterUpgrade.use(ShooterUpgrade.java:108) ~[simpleplanes-1.19.2-5.2.2.jar%23270!/:1.19.2-5.2.2] {re:classloading}
	at xyz.przemyk.simpleplanes.entities.PlaneEntity.m_6469_(PlaneEntity.java:287) ~[simpleplanes-1.19.2-5.2.2.jar%23270!/:1.19.2-5.2.2] {re:classloading}
