### ISSUE TITLE
Error executing task on client Ram Leak

### ISSUE THREAD

**Issue by dbock1989** [przemykomo/simple-planes#19]
So im having a ram leak leading to spammed logs and minecraft eventually shutting down. The only thing I could find that I think was useful leading here was this insert:

[18:31:23] [Render thread/FATAL]: Error executing task on Client
java.lang.IllegalStateException: handling packet in ResourceKey[minecraft:dimension / minecraft:overworld]
	at com.qouteall.hiding_in_the_bushes.network.StcRedirected.doProcessRedirectedPacket(StcRedirected.java:89) ~[?:0.2]
	at com.qouteall.hiding_in_the_bushes.network.StcRedirected.lambda$handle$0(StcRedirected.java:119) ~[?:0.2]
	at com.qouteall.hiding_in_the_bushes.network.StcRedirected$$Lambda$20483/508647248.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?]
	at com.qouteall.hiding_in_the_bushes.network.StcRedirected.handle(StcRedirected.java:119) ~[?:0.2]
	at com.qouteall.hiding_in_the_bushes.network.NetworkMain$$Lambda$14910/314975213.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$19590/2102903922.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2817/2031234911.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2819/1774714488.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:73) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$19577/352877318.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:73) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1926) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$19667/1192229584.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:922) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.108.jar:32.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/1137662975.call(Unknown Source) [forge-1.16.1-32.0.108.jar:32.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]
Caused by: java.lang.IllegalStateException: Invalid entity data item type for field 10 on entity PlaneEntity['Oak Furnace Plane'/78672, l='ClientLevel', x=988.69, y=64.00, z=830.46]: old=Quaternion[1.0 + 0.0i + 0.0j + 0.0k](class net.minecraft.util.math.vector.Quaternion), new=Optional.empty(class java.util.Optional)
	at net.minecraft.network.datasync.EntityDataManager.func_187224_a(EntityDataManager.java:245) ~[?:?]
	at net.minecraft.network.datasync.EntityDataManager.func_187218_a(EntityDataManager.java:233) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147284_a(ClientPlayNetHandler.java:556) ~[?:?]
	at net.minecraft.network.play.server.SEntityMetadataPacket.func_148833_a(SourceFile:42) ~[?:?]
	at net.minecraft.network.play.server.SEntityMetadataPacket.func_148833_a(SourceFile:11) ~[?:?]
	at com.qouteall.hiding_in_the_bushes.network.StcRedirected.doProcessRedirectedPacket(StcRedirected.java:84) ~[?:0.2]
	... 44 more
[18:31:24] [Render thread/FATAL]: Error executing task on Client
io.netty.handler.codec.DecoderException: Unknown serializer type 53
	at net.minecraft.network.datasync.EntityDataManager.func_187215_b(EntityDataManager.java:213) ~[?:?]
	at net.minecraft.network.play.server.SEntityMetadataPacket.func_148837_a(SourceFile:31) ~[?:?]
	at com.qouteall.hiding_in_the_bushes.network.StcRedirected.<init>(StcRedirected.java:51) ~[?:0.2]
	at com.qouteall.hiding_in_the_bushes.network.NetworkMain$$Lambda$14905/1892659744.apply(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:120) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$19586/673801568.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:120) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2817/2031234911.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2819/1774714488.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:73) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$19577/352877318.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:73) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1926) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$19667/1192229584.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:922) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.108.jar:32.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/1137662975.call(Unknown Source) [forge-1.16.1-32.0.108.jar:32.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]

I dont know 100% that its this mods fault but its listed as cause by the plane.

I have the whole log file if you need it!
[2020-08-28-1.log](https://github.com/przemykomo/simple-planes/files/5144452/2020-08-28-1.log)

BTW LOVE YOUR MOD, good job!!

**Comment by przemykomo** [comment]
I see you are using the 1.16.1 version. Quaternion serializers (which are propably the issue) were fixed in 1.16.2 mod version. I'll port it to 1.16.1

**Comment by dbock1989** [comment]
Wow! I apprciate it so much! Thank you!

**Comment by przemykomo** [comment]
Ok, I ported it to 1.16.1, but don't expect more support on this version. I just uploaded 1.16.1-2.0.5.3 to curseforge.
