### ISSUE TITLE
Preventable Recipe Logspam 

### ISSUE THREAD

**Issue by Partonetrain** [przemykomo/simple-planes#20]
Biomes' O Plenty plane recipes try to load regardless of if BoP is present or not, creating lots of logspam:

```
com.google.gson.JsonSyntaxException: Unknown item 'biomesoplenty:palm_boat'
	at net.minecraft.item.crafting.Ingredient.lambda$deserializeItemList$11(Ingredient.java:216) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_265]
	at net.minecraft.item.crafting.Ingredient.func_199803_a(Ingredient.java:215) ~[?:?]
       .....
```

This can be prevented by a recipe condition like so:
```
"conditions": [
    {
      "type": "forge:mod_loaded",
      "modid": "bop"
    }
  ]
```
(not actually sure if that's the modid)

**Comment by adoxentor** [comment]
will be fixed in helicopter update
