### ISSUE TITLE
Cannot put down a plane with right click, in 1.12.2

### ISSUE THREAD

**Issue by rzchar** [przemykomo/simple-planes#28]
forge version 8.0.99.99

[23:46:21] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Unregistered serializer xyz.przemyk.simpleplanes.setup.SimplePlanesDataSerializers$1@201fcfd for 11!
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.IllegalArgumentException: Unregistered serializer xyz.przemyk.simpleplanes.setup.SimplePlanesDataSerializers$1@201fcfd for 11!
	at net.minecraft.network.datasync.EntityDataManager.func_187214_a(EntityDataManager.java:117) ~[nb.class:?]
	at xyz.przemyk.simpleplanes.entities.PlaneEntity.func_70088_a(PlaneEntity.java:127) ~[PlaneEntity.class:?]
	at net.minecraft.entity.Entity.<init>(Entity.java:217) ~[vg.class:?]
	at xyz.przemyk.simpleplanes.entities.PlaneEntity.<init>(PlaneEntity.java:103) ~[PlaneEntity.class:?]
	at xyz.przemyk.simpleplanes.entities.LargePlaneEntity.<init>(LargePlaneEntity.java:26) ~[LargePlaneEntity.class:?]
	at xyz.przemyk.simpleplanes.entities.MegaPlaneEntity.<init>(MegaPlaneEntity.java:39) ~[MegaPlaneEntity.class:?]
	at xyz.przemyk.simpleplanes.setup.SimplePlanesItems.lambda$init$3(SimplePlanesItems.java:46) ~[SimplePlanesItems.class:?]
	at xyz.przemyk.simpleplanes.items.PlaneItem.func_77659_a(PlaneItem.java:91) ~[PlaneItem.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by rzchar** [comment]
Update forge to 14.23.5.2772 and issue remains.

**Comment by Zuosizhu** [comment]
Have the same problem with you
